/**
 * @file lv_port_indev.h
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool.
 */

#ifndef LV_PORT_INDEV_H
#define LV_PORT_INDEV_H

/*********************
 *      INCLUDES
 *********************/
#include "lvgl/lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/*********************
 *      DEFINES
 *********************/

/**********************
 *      TYPEDEFS
 **********************/

/**********************
 * GLOBAL PROTOTYPES
 **********************/

void lv_port_indev_init(void);

/**********************
 *      MACROS
 **********************/


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /*LV_PORT_INDEV_H*/
