/*
 * ti_lvgl_disp_interface.c
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool.
 */


/*********************
 *      INCLUDES
 *********************/
#include <ti_lvgl_disp_interface.h>
#include <lv_drv_conf.h>

/* SPI driver handle */
SPI_Handle masterSpi;

/*********************
 *      FUNCTIONS
 *********************/

/**
 * Initialize the software spi port
 */
void spi_init(void)
{
    SPI_Params      spiParams;

    /* Open SPI as master (default) and initialize to default parameters.
     * Set frame format to use freescale SPI mode and bit rate to 15 MHz */
    SPI_init();

    SPI_Params_init(&spiParams);
    spiParams.frameFormat = SPI_POL0_PHA0;
    spiParams.bitRate = LV_DRV_DISP_SPI_BITRATE;

    masterSpi = SPI_open(CONFIG_SPI_0, &spiParams);

    if (masterSpi == NULL) {
        /*Error initializing master SPI*/
        /* INFINITE_LOOP.LOCAL */
        while (1);
    }
}

/**
 * Write byte to the spi port
 * @param b a byte to write
 */
void spi_wr_byte(uint8_t b)
{
    uint8_t pui8Data[1];
    SPI_Transaction transaction;
    bool            transferOK;

    /* Write the data byte to the bus. */
    pui8Data[0] = b;

    transaction.count = 1;
    transaction.txBuf = (void *)pui8Data;
    transaction.rxBuf = NULL;
    transferOK = SPI_transfer(masterSpi, &transaction);
    if (!transferOK) {
        /* INFINITE_LOOP.LOCAL */
        while(1) {}
    }
}

/**
 * Write word to the spi port
 * @param w a word to write
 */
void spi_wr_word(uint16_t w)
{
    uint8_t pui8Data[2];
    SPI_Transaction transaction;
    bool            transferOK;

    /* Write the most significant byte of the data to the bus. */
    pui8Data[0] = (w >> 8);

    /* Write the least significant byte of the data to the bus. */
    pui8Data[1] = w;

    transaction.count = 2;
    transaction.txBuf = (void *)pui8Data;
    transaction.rxBuf = NULL;
    transferOK = SPI_transfer(masterSpi, &transaction);
    if (!transferOK) {
        /* INFINITE_LOOP.LOCAL */
        while(1) {}
    }
}

/**
 * Write an array to the spi port
 * @param array pointer to a memory block to write
 * @param length number of bytes to write
 */
void spi_wr_array(uint8_t * array, uint32_t length)
{
    SPI_Transaction transaction;
    bool            transferOK;
    transaction.count = length;
    transaction.txBuf = array;
    transaction.rxBuf = NULL;
    transferOK = SPI_transfer(masterSpi, &transaction);
    if (!transferOK) {
        /* INFINITE_LOOP.LOCAL */
        while(1) {}
    }
}

