/*
 * ti_lvgl_disp_interface.h
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool.
 */

#ifndef TI_LVGL_DISP_INTERFACE_H_
#define TI_LVGL_DISP_INTERFACE_H_


#include <stdint.h>
#include <stdbool.h>
#include <ti/drivers/GPIO.h>
#include <ti/drivers/SPI.h>
#include "ti_drivers_config.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Initialize the software spi port
 */
void spi_init(void);

/**
 * Write byte to the spi port
 * @param b a byte to write
 */
void spi_wr_byte(uint8_t b);

/**
 * Write word to the spi port
 * @param w a word to write
 */
void spi_wr_word(uint16_t w);

/**
 * Write an array to the spi port
 * @param array pointer to a memory block to write
 * @param length number of bytes to write
 */
void spi_wr_array(uint8_t * array, uint32_t length);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* TI_LVGL_DISP_INTERFACE_H_ */
